### ISSUE TITLE
Allow bech32 > 90 characters

### ISSUE THREAD

**Issue by nielspeen** [Bit-Wasp/bech32#3]
Please allow bech32 strings to be larger than 90 characters, to support the decoding of BOLT11.

**Comment by afk11** [comment]
Holy cow there's people working on BOLT stuff with this library? That's awesome :+1: 

I noticed that too. I'll look into refactoring things so it's allowed.. The bech32 specification says they're 90 characters, so maybe we can have another class for these.

As an aside, it's probably time for us to start implementing those messages as a package here. Or maybe you've already started work on this?

**Comment by afk11** [comment]
Oh, I just realized this isn't the code I had been using in bitcoin-php :/ I intended to write this for a codebase that couldn't use bitcoin-php, but in the end it wasn't required.

It may be less tested than that implementation, though I'll eventually port everything to here and depend on this package. Just a heads up, maybe pull in bitwasp/bitcoin to be sure

**Comment by afk11** [comment]
@nielspeen https://github.com/Bit-Wasp/bech32/blob/e1ea58c848a4ec59d81b697b3dfe9cc99968d0e7/src/bech32.php#L160 v0.0.1 exposese decodeRaw, basically the same as decode but without the max length check
