### ISSUE TITLE
Do you know how to get an address from a segwit transaction?

### ISSUE THREAD

**Issue by 77381110** [Bit-Wasp/bech32#5]
**I use bitcoin-cli to view a transaction like the following command：**
bitcoin-cli getrawtransaction '01d94dae5f2e972682e4f33fa0e6b83ab812a2d344d13262135e1acc73832f0d' 1.
**In the result returned, Vout has no accurate addresses.**
and the result is as follows：
 "vout": [
    {
      "value": 10.00910000,
      "valueSat": 1000910000,
      "n": 1,
      "scriptPubKey": {
        "asm": "0 701a8d401c84fb13e6baf169d59684e17abd9fa216c8cc5b9fc63d622ff8c58d",
        "hex": "0020701a8d401c84fb13e6baf169d59684e17abd9fa216c8cc5b9fc63d622ff8c58d",
        "reqSigs": 1,
        "type": "witness_v0_scripthash",
        "addresses": [
          "3QJmnh"
        ]
      }
    }
  ],
**You know whether you can get the bech32 address through the above scriptPubKey.**
**Thank you very much.**

**Comment by afk11** [comment]
I would suggest using bitwasp/bitcoin and not this library directly.

But if you really want to do it yourself, take a look at the test cases, and try adding an extra one so you understand what inputs are required
https://github.com/Bit-Wasp/bech32/blob/master/test/SegwitAddressTest.php#L28

**Comment by 77381110** [comment]
Thank you so much!

**Comment by afk11** [comment]
Np, any time
